config/routes.rb
SimulacionApp::Application.routes.draw do

  namespace :random do
     resources :gna do
       get :generate_form, :on=>:collection
       post :generate, :on=>:collection
       get :results, :on=>:collection
     end
  end

end

app/models/gna.rb
class Gna < ActiveRecord::Base

	def random_numbers
		first_num = seed_xo
		r = -1
		randoms = Array.new
		xo=seed_xo
		while r!=first_num do
			xo=((xo*multiplier_a+constant_c)%module_m)
			r=xo
			puts r
			randoms << r			
			if randoms.count==50
				break
			end
		end
		randoms
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/random/gna_controller.rb
class Random::GnaController < ApplicationController
  def index
  end

  def generate_form
  	@gna = Gna.new
  end

  def generate
  	@gna = Gna.new(params[:gna])
  	@randoms_array = @gna.random_numbers
  	respond_to do |format|
  		format.html { redirect_to("/random/gna/generate_form", :notice => 'Post created.') }  
      format.js 
    end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Allows to set the _title_ header.
  #
  # * *args*
  #   - title(_string_) -> title name to be set   
  def title(title)
    content_for(:title) {title}
  end

  # Allows to add the javascript files into the header.
  #
  # * *args*
  #   - files(_string_) -> list of javascript files, comma separated
  def javascript(*files)
    content_for(:head) {javascript_include_tag(*files)}
  end

  # Allows to add the stylesheet files into the header.
  #
  # * *args*
  #   - files(_string_) -> list of stylesheet files, comma separated
  def stylesheet(*files)
    content_for(:head) {stylesheet_link_tag(*files)}
  end

  # This function is used in forms to indicate if a field is required or not.
  #
  # * *args*
  #   - nullable(_bool_)
  # * *returns*
  #   - a red-colored * if nullable
  def set_label_obligatory(nullable)
    return (nullable)? "":"<span style=\"color:red\">(*) </span>".html_safe
  end

  # This function is used in the jquery validations to indicate if a field is optional or required
  #
  # * *args*
  #   - nullable(_bool_)
  # * *returns*
  #   - optional or required
  def set_validate(nullable)
    return (nullable)? "optional":"required"
  end

  # This function disable all input field in a specified form. Buttons are omitted
  #
  # * *args*
  #   - form(_string_) -> the form id which inputs will be disabled
  def disabled_info(form)
    "<script type='text/javascript'>
      $().ready(function() {
  		  $('##{form} :input').attr('disabled', true);
  		  $('##{form} :input.button').attr('disabled', false);
      });</script>".html_safe
  end

  # This function implements the loading gif when the specified search form is submitted
  #
  # * *args*
  #   - form(_string_) -> the search form id
  def search_loading_js form
    "<script type='text/javascript'>
      $('##{form}').bind('ajax:before', function() {
        load_close('loading_search');
      }).bind('ajax:success', function() {
        load_off('loading_search');
      });
    </script>".html_safe
  end

  # This functions allows paginate works via ajax calls
  def paginate_ajax_js
    "<script>
      $(document).ready(function() {
      $('.pagination a').attr('data-remote', 'true');
    });</script>".html_safe
  end
  
  def broadcast(channel, &block)
    message = {:channel => channel, :data => capture(&block), :ext => {:auth_token => FAYE_TOKEN}}
    uri = URI.parse("http://192.168.1.35:9292/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, '#{association}', '#{escape_javascript(fields)}')", :class =>'add')
  end


end

app/helpers/random/gna_helper.rb
module Random::GnaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimulacionApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/random/gna/_random_numbers.html.erb
<p>Results</p>
<%=@randoms_array%>

app/views/random/gna/generate.js.erb
$("#div_results").html("<%= escape_javascript(render :partial=>'random_numbers') %>");

app/views/random/gna/generate_form.html.erb
<h1>Generador de Números Aleatorios</h1>

<h2>Método de Congruencia Lineal</h2>

<%=form_for(@gna,:url=>generate_random_gna_index_path,:method=>:post,:remote=>true) do |f|%>
	<fieldset>
      <legend><%=t('.gna_legend')%></legend>
      <dl class="inline">
      	<dt><%=f.label :multiplier_a, 'Multiplier (a)'%></dt>
		<dd>
          <%= f.text_field :multiplier_a, :class=>"medium validate[#{set_validate(false)}]",:size=>50 %>
        </dd>
		<dt><%=f.label :constant_c, 'Constant (c)'%></dt>
		<dd>
          <%= f.text_field :constant_c, :class=>"medium validate[#{set_validate(false)}]",:size=>50 %>
        </dd>
		<dt><%=f.label :module_m,'Module (m)'%></dt>
		<dd>
          <%= f.text_field :module_m, :class=>"medium validate[#{set_validate(false)}]",:size=>50 %>
        </dd>
		<dt><%=f.label :seed_xo,'Seed (Xo)'%></dt>
		<dd>
          <%= f.text_field :seed_xo, :class=>"medium validate[#{set_validate(false)}]",:size=>50 %>
        </dd>
      </dl>
    </fieldset>
  	<%=f.submit t('buttons.save'), :disable_with => t('buttons.processing'), :class => "btn btn-success"%>  
<%end%>

<div id="div_results">
</div>

app/views/random/gna/index.html.erb
<h1>Generador de Números Aleatorios</h1>

<h2>Método de Congruencia Lineal</h2>

<p>Lorem ipsumn asdde ashlkas ashkasscnx.orem ipsumn asdde ashlkas ashkasscnx. orem ipsumn asdde ashlkas ashkasscnx.</p>

<a href="/random/gna/generate_form">Ir al generador</a>